### PR TITLE
Added a time filter

### PR DESCRIPTION
**Pull request by lorcan**
Added a time filter, based on the existing date filter.

### CODE REVIEW

**Comment by lorcan** [comment]
I'd be happy to also backfill the [Filtering-Input docs](https://github.com/cypriss/mutations/wiki/Filtering-Input) with the missing sections (`date`, `float`, etc.), as well as `time` if this PR looks good to merge.

**Comment by openface** [comment]
+1

**Comment by destroytoday** [comment]
+1

**Comment by elfassy** [comment]
+1

**Comment by sskylar** [comment]
+1

**Comment by elfassy** [comment]
should there be timezones by default?
```
          actual_time = if options[:format]
            Time.strptime(data, options[:format])
          else
            Time.parse(data)
          end
#vs
          actual_time = if options[:format]
            Time.strptime(data, options[:format]).in_time_zone
          else
            Time.zone.parse(data)
          end
```

**Comment by jkogara** [comment]
+1

**Comment by psyho** [comment]
+1

**Comment by SeanSmithers** [comment]
+1

Bump! Would be great to get this merged

**Comment by patrickod** [comment]
@lorcan mind rebasing onto latest master w/ updated test matrix and then we can merge this in and bump to `0.8.0` ?

**Comment by lorcan** [comment]
👍  I've rebased and we're 🍏  across the test matrix.

**Comment by GavinJoyce** [comment]
Perhaps add some docs to https://github.com/cypriss/mutations/wiki/Filtering-Input?

**Comment by lorcan** [comment]
Yup, I'll take on improving the documentation in the coming week.

**Pull request merged**
